//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 15/05/2015 10:01:12
namespace ClientPCL.ServicoREST.Models
{
    /// <summary>
    /// There are no comments for PessoasSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PessoasSingle")]
    public partial class PessoasSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Pessoas>
    {
        /// <summary>
        /// Initialize a new PessoasSingle object.
        /// </summary>
        public PessoasSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PessoasSingle object.
        /// </summary>
        public PessoasSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PessoasSingle object.
        /// </summary>
        public PessoasSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Pessoas> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Pessoas in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdPessoa
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("idPessoa")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Pessoas")]
    public partial class Pessoas : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Pessoas object.
        /// </summary>
        /// <param name="idPessoa">Initial value of IdPessoa.</param>
        /// <param name="nome">Initial value of Nome.</param>
        /// <param name="telefone">Initial value of Telefone.</param>
        /// <param name="ativo">Initial value of Ativo.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        public static Pessoas CreatePessoas(int idPessoa, string nome, string telefone, bool ativo)
        {
            Pessoas pessoas = new Pessoas();
            pessoas.IdPessoa = idPessoa;
            pessoas.Nome = nome;
            pessoas.Telefone = telefone;
            pessoas.Ativo = ativo;
            return pessoas;
        }
        /// <summary>
        /// There are no comments for Property IdPessoa in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("idPessoa")]
        public int IdPessoa
        {
            get
            {
                return this._IdPessoa;
            }
            set
            {
                this.OnIdPessoaChanging(value);
                this._IdPessoa = value;
                this.OnIdPessoaChanged();
                this.OnPropertyChanged("idPessoa");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _IdPessoa;
        partial void OnIdPessoaChanging(int value);
        partial void OnIdPessoaChanged();
        /// <summary>
        /// There are no comments for Property Nome in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("nome")]
        public string Nome
        {
            get
            {
                return this._Nome;
            }
            set
            {
                this.OnNomeChanging(value);
                this._Nome = value;
                this.OnNomeChanged();
                this.OnPropertyChanged("nome");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private string _Nome;
        partial void OnNomeChanging(string value);
        partial void OnNomeChanged();
        /// <summary>
        /// There are no comments for Property Telefone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("telefone")]
        public string Telefone
        {
            get
            {
                return this._Telefone;
            }
            set
            {
                this.OnTelefoneChanging(value);
                this._Telefone = value;
                this.OnTelefoneChanged();
                this.OnPropertyChanged("telefone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private string _Telefone;
        partial void OnTelefoneChanging(string value);
        partial void OnTelefoneChanged();
        /// <summary>
        /// There are no comments for Property Ativo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ativo")]
        public bool Ativo
        {
            get
            {
                return this._Ativo;
            }
            set
            {
                this.OnAtivoChanging(value);
                this._Ativo = value;
                this.OnAtivoChanged();
                this.OnPropertyChanged("ativo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private bool _Ativo;
        partial void OnAtivoChanging(bool value);
        partial void OnAtivoChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::ClientPCL.ServicoREST.Models.Pessoas as global::ClientPCL.ServicoREST.Models.PessoasSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ClientPCL.ServicoREST.Models.PessoasSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ClientPCL.ServicoREST.Models.Pessoas> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ClientPCL.ServicoREST.Models.PessoasSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ClientPCL.ServicoREST.Models.Pessoas as global::ClientPCL.ServicoREST.Models.PessoasSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="idPessoa">The value of idPessoa</param>
        public static global::ClientPCL.ServicoREST.Models.PessoasSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ClientPCL.ServicoREST.Models.Pessoas> source,
            int idPessoa)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "idPessoa", idPessoa }
            };
            return new global::ClientPCL.ServicoREST.Models.PessoasSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace ClientPCL.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "ServicoREST.Models", "ClientPCL.ServicoREST.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "ClientPCL.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("ClientPCL.ServicoREST.Models", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("ServicoREST.Models.", originalNameAttribute.OriginalName);
                }
                return string.Concat("ServicoREST.Models.", clientType.Name);
            }
            if (clientType.Namespace.Equals("ClientPCL.Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for PessoasOData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PessoasOData")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ClientPCL.ServicoREST.Models.Pessoas> PessoasOData
        {
            get
            {
                if ((this._PessoasOData == null))
                {
                    this._PessoasOData = base.CreateQuery<global::ClientPCL.ServicoREST.Models.Pessoas>("PessoasOData");
                }
                return this._PessoasOData;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ClientPCL.ServicoREST.Models.Pessoas> _PessoasOData;
        /// <summary>
        /// There are no comments for PessoasOData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        public void AddToPessoasOData(global::ClientPCL.ServicoREST.Models.Pessoas pessoas)
        {
            base.AddObject("PessoasOData", pessoas);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""ServicoREST.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Pessoas"">
        <Key>
          <PropertyRef Name=""idPessoa"" />
        </Key>
        <Property Name=""idPessoa"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""nome"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""telefone"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""ativo"" Type=""Edm.Boolean"" Nullable=""false"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""PessoasOData"" EntityType=""ServicoREST.Models.Pessoas"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
